name: instant_memo
description: Quick memo app to capture fleeting thoughts.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  google_mobile_ads: ^5.1.0
  shared_preferences: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#6750A4"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true
